### ISSUE TITLE
exposing password data in the output

### ISSUE THREAD

**Issue by sugitk** [infobloxopen/infoblox-ansible#41]
When using `infoblox.nios_modules.nios_cname_record` module for example, the output shows the provider data and it includes the password data which should be hidden.  It should be replaced with `VALUE_SPECIFIED_IN_NO_LOG_PARAMETER`.

We suppose this is not a specific issue on this module, but all modules in this collection may have the same problem.

```
{
    "changed": true,
    "invocation": {
        "module_args": {
            "name": "host01.example.com",
            "canonical": "host01.example.com",
            "view": "Example View",
            "state": "present",
            "provider": {
                "host": "10.0.0.1",
                "validate_certs": false,
                "wapi_version": "2.1",
                "username": "admin",
                "password": "a_password_string_to_be_hidden",
                "silent_ssl_warnings": true,
                "http_request_timeout": 10,
                "http_pool_connections": 10,
                "http_pool_maxsize": 10,
                "max_retries": 3,
                "max_results": 1000
            },
            "ttl": null,
            "extattrs": null,
            "comment": null
        }
    },
    "_ansible_no_log": false
}
```

**Comment by badnetmask** [comment]
Looking at the code, [this line](https://github.com/infobloxopen/infoblox-ansible/blob/master/ansible_collections/infoblox/nios_modules/plugins/module_utils/api.py#L72) basically hardcodes the `no_log` option, which makes it very hard to override.
However, I was able to reproduce it by removing the `password` option from my playbooks, and exporting the `INFOBLOX_PASSWORD` as an environment variable.
If this is your case (using the environment variable), it seems to me like this is a bug with in the [Ansible code](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/common/parameters.py#L258), rather than the Infoblox module.

**Comment by sugitk** [comment]
@badnetmask Thank you for your investigation.  I also reviewed the code and I've submitted an issue to ansible/ansible.

**Comment by badnetmask** [comment]
Ref: https://github.com/ansible/ansible/issues/73620

**Comment by badnetmask** [comment]
@sugitk - since this was resolved on the Ansible side, do you mind closing this bug? I don't have access to do it. Thank you.

**Comment by sugitk** [comment]
@badnetmask Thank you, I will close this issue as per fixed in the ansible side.
